print("Mad Lib : Horror Movies")
print()

adj1 = input("What is an adjective? ")
pnoun1 = input("What is a plural noun? ")
adj2 = input("What is another adjective? ")
body_part1 = input("What is a part of the body? ")
body_part2 = input("What is another part of the body? ")
noun1 = input("What is a noun? ")
noun2 = input("What is another noun? ")
noun3 = input("What is another noun? ")
noun4 = input("What is another noun? ")
noun5 = input("What is another noun? ")
noun6 = input("What is another noun? ")
adj3 = input("What is another adjective? ")
noun7 = input("What is another noun? ")
noun8 = input("What is another noun? ")

print("Here is the list of the most %s horror %s ever made in Hollywood!" % (adj1, pnoun1))
print("Each of these %s films received a rating of two %s." % (adj2, body_part1))
print("1. The Hunch%s of Notre %s" % (body_part2, noun1))
print("2. The %s of the Living %s" % (noun2, noun3))
print("3. %s of Frankenstein" % noun4)
print("4. Invasion on the %s Snatchers" % noun5)
print("5. %s from the %s Lagoon" % (noun6, adj3))
print("6. Last %s on the Left" % noun7)
print("7. The %s of the Opera" % noun8)
