print("Mad Lib : Horror Movies")
print()

words = []

words.append(input("What is an adjective? "))
words.append(input("What is a plural noun? "))
words.append(input("What is another adjective? "))
words.append(input("What is a part of the body? "))
words.append(input("What is another part of the body? "))
words.append(input("What is a noun? "))
words.append(input("What is another noun? "))
words.append(input("What is another noun? "))
words.append(input("What is another noun? "))
words.append(input("What is another noun? "))
words.append(input("What is another noun? "))
words.append(input("What is another adjective? "))
words.append(input("What is another noun? "))
words.append(input("What is another noun? "))

print("Here is the list of the most %s horror %s ever made in Hollywood!" % (words[0], words[1]))
print("Each of these %s films received a rating of two %s." % (words[2], words[3]))
print("1. The Hunch%s of Notre %s" % (words[4], words[5]))
print("2. The %s of the Living %s" % (words[6], words[7]))
print("3. %s of Frankenstein" % words[8])
print("4. Invasion on the %s Snatchers" % words[9])
print("5. %s from the %s Lagoon" % (words[10], words[11]))
print("6. Last %s on the Left" % words[12])
print("7. The %s of the Opera" % words[13])
